import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MSWComponent } from "./_component/MSWConponent";
import AuthSession from "./_component/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pjoject_x",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const baseUrl2 = process.env.NEXT_PUBLIC_BASE_URL2;
console.log("baseUrl2", baseUrl2);

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
